In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
file_path = 'C:\\hudsondata\\Machine Learning\\Redhat'
acttest = pd.read_csv(os.path.join(file_path,'act_test.csv'))
acttrain = pd.read_csv(os.path.join(file_path,'act_train.csv'))
people = pd.read_csv(os.path.join(file_path,'people.csv'))

In [3]:
people = people.replace({'type':'','group':'','ppl_':''},regex=True)
acttrain = acttrain.replace({'type':'','group':'','ppl_':''},regex=True)
acttrain = acttrain.fillna('-1')
acttest = acttest.replace({'type':'','group':'','ppl_':''},regex=True)
acttest = acttest.fillna('-1')

In [6]:
joined_train=pd.merge(people, acttrain, on='people_id')
joined_test=pd.merge(people, acttest, on='people_id')

In [9]:
a=dict()
b=dict()

In [ ]:
#did not include char_38 because it is a continuous variable and will most likely decrease the predictive capability of naive bayes given its continuous form
#first - extract all data from 0 outcome
#second - get all the unique values from that column (regardless of outcome) and append to first extraction to make sure all values are represented
#third - given the outcome, get the probabilities of each value for each column
#fourth - get the negative log probability of each and store all in a dictionary, this way we allow to computer to work with manageable values (not super small)
# fifth - do the same for outcome 1

In [11]:
for name in joined_train.columns.values:
    if name!= 'people_id' and name!= 'activity_id' and name!='date_x' and name!='date_y'and name!='char_38':
        print name
        a[name] = joined_train[joined_train['outcome']==0][name]
        a[name] = a[name].append(pd.DataFrame({0:joined_train[name].unique()}))[0]
        a[name] = -np.log(a[name].value_counts(dropna=False)/len(a[name]))
        a[name] = dict(a[name])
        b[name] = joined_train[joined_train['outcome']==1][name]
        b[name] = b[name].append(pd.DataFrame({0:joined_train[name].unique()}))[0]
        b[name] = -np.log(b[name].value_counts(dropna=False)/len(b[name]))
        b[name] = dict(b[name])

char_1_x
group_1
char_2_x
char_3_x
char_4_x
char_5_x
char_6_x
char_7_x
char_8_x
char_9_x
char_10_x
char_11
char_12
char_13
char_14
char_15
char_16
char_17
char_18
char_19
char_20
char_21
char_22
char_23
char_24
char_25
char_26
char_27
char_28
char_29
char_30
char_31
char_32
char_33
char_34
char_35
char_36
char_37
activity_category
char_1_y
char_2_y
char_3_y
char_4_y
char_5_y
char_6_y
char_7_y
char_8_y
char_9_y
char_10_y
outcome


In [12]:
aa = np.zeros(len(joined_test))
bb = np.zeros(len(joined_test))

In [14]:
b

{'activity_category': {' 1': 2.7111549518898426,
  ' 2': 0.74807791811788116,
  ' 3': 2.1989082011870695,
  ' 4': 2.2629545770819717,
  ' 5': 1.4205599288383588,
  ' 6': 6.0221762385721647,
  ' 7': 6.6494644171477066},
 'char_10_x': {False: 0.46216298895095975, True: 0.99403516618248511},
 'char_10_y': {' 3206': 9.6702254404930912,
  ' 7273': 12.698747536870073,
  ' 3204': 12.698747536870073,
  ' 7270': 12.698747536870073,
  ' 3202': 10.242011764048769,
  ' 7276': 13.104212644978238,
  ' 3200': 10.430063995551709,
  ' 7272': 12.187921913104082,
  ' 7279': 13.104212644978238,
  ' 7278': 13.797359825538184,
  ' 7271': 13.104212644978238,
  ' 3208': 13.797359825538184,
  ' 7277': 13.797359825538184,
  ' 4820': 8.9690460882358813,
  ' 3203': 13.797359825538184,
  ' 1932': 13.104212644978238,
  ' 1933': 13.104212644978238,
  ' 1930': 12.411065464418293,
  ' 1931': 13.797359825538184,
  ' 1936': 10.752837387814759,
  ' 1937': 12.005600356310127,
  ' 1934': 12.187921913104082,
  ' 1935': 11.1

In [15]:
for name in joined_test.columns.values:
    if name != 'people_id' and name != 'activity_id' and name != 'date_x' and name != 'date_y' and \
       name != 'char_38' and name != 'group_1' and name != 'char_10_y':
            print name
            aa = aa + np.array([a[name][x] for x in joined_test[name]])
            bb = bb + np.array([b[name][x] for x in joined_test[name]])

char_1_x
char_2_x
char_3_x
char_4_x
char_5_x
char_6_x
char_7_x
char_8_x
char_9_x
char_10_x
char_11
char_12
char_13
char_14
char_15
char_16
char_17
char_18
char_19
char_20
char_21
char_22
char_23
char_24
char_25
char_26
char_27
char_28
char_29
char_30
char_31
char_32
char_33
char_34
char_35
char_36
char_37
activity_category
char_1_y
char_2_y
char_3_y
char_4_y
char_5_y
char_6_y
char_7_y
char_8_y
char_9_y


In [20]:
np.array([a['char_1_x'][x] for x in joined_test['char_1_x']])

array([ 0.05346433,  0.05346433,  0.05346433, ...,  0.05346433,
        0.05346433,  0.05346433])

In [21]:
a['char_1_x']

{' 1': 2.9553536591693832, ' 2': 0.053464329101592309}

In [24]:
aa

array([ 104.67651667,   64.17311947,  110.36379727, ...,   19.40749993,
         19.40749993,   19.40749993])

In [ ]:
#from all the inverse logarithm probability of every char (feature),we added everything up and we then use np.argmin to give us the smaller number between
# the two and whichever that is - that is our prediction - which is either 0 or 1

In [26]:
submission=pd.DataFrame({'activity_id':acttest['activity_id'], 'outcome':np.argmin(np.concatenate((aa, bb)).reshape((2, len(aa))).T, 1)})

In [34]:
np.argmin(np.concatenate((aa,bb)).reshape((2,len(aa))).T,1)

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [42]:
submission.to_csv('submission.csv',index=False)

In [43]:
submission.head()

activity_id  outcome
0   act1_249281        1
1   act2_230855        1
2   act1_240724        1
3    act1_83552        1
4  act2_1043301        1

In [44]:
-np.log(0.5)

0.69314718055994529

In [45]:
-np.log(0.1)

2.3025850929940455

In [46]:
-np.log(0)

inf